sudo: required
services:
  - docker

before_install:
  - docker build -t siyagwala/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true siyagwala/react-test npm test

after_success:
  - docker buil -t siyagwala/multi-client ./client
  - docker buil -t siyagwala/multi-nginx ./nginx
  - docker buil -t siyagwala/multi-server ./server
  - docker buil -t siyagwala/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin  
  # Take those images and push them to docker hub
  - docker push siyagwala/multi-client
  - docker push siyagwala/multi-nginx
  - docker push siyagwala/multi-server
  - docker push siyagwala/multi-worker

